version: '3.9'
services:
  app:
    container_name: nuxi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    env_file:
      - .env
    volumes:
      - .:/app